# Generated by Django 4.2.16 on 2025-05-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion_report',
        ),
        migrations.RemoveField(
            model_name='task',
            name='worked_hours',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
