# Generated by Django 4.2.16 on 2025-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_completion_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='User', max_length=20),
        ),
    ]
